// Page Action Types
export const CLICK_SHOW_CALCULATOR = 'CLICK_SHOW_CALCULATOR';

export const CLICK_OUTSIDE_CALCULATOR = 'CLICK_OUTSIDE_CALCULATOR';

// Calculate Action Types
export const SET_CALCULATION_STATEMENT = 'SET_CALCULATION_STATEMENT';

export const CLEAR_CALCULATION_STATEMENT = 'CLEAR_CALCULATION_STATEMENT';

export const TAKE_INVERSE = 'TAKE_INVERSE';

export const EVALUATE_CALCULATION_STATEMENT = 'EVALUATE_CALCULATION_STATEMENT';


