export const SET_CALCULATION_STATEMENT = 'SET_CALCULATION_STATEMENT';

export const CLEAR_CALCULATION_STATEMENT = 'CLEAR_CALCULATION_STATEMENT';

export const TAKE_INVERSE = 'TAKE_INVERSE';

export const EVALUATE_CALCULATION_STATEMENT = 'EVALUATE_CALCULATION_STATEMENT';
